### ISSUE TITLE
Configure PR and Issue Templates

### ISSUE THREAD

**Issue by omusavi** [benchpress-team/.github#1]
---
name: User Story
about: Create a new user story issue
title: Configure PR and Issue Templates
labels: user story
assignees: ''
---

Creating an organization wide template will ensure all repos in this 
organization get the same templates (and hopefully to draft issues as well)

## Acceptance Criteria

(Should contain action and result)

- Pull request template checked in and should be accessible and a new pull request creation should start with its contents. 
- Bug template checked in and should be accessible and a new Bug report should start with its contents. 
- Feature or User Story template checked in and should be accessible and a new Feature or User Story creation should start with its contents.
- Task template checked in and should be accessible and a new Task creation should start with its contents. 
- TODO template checked in and should be accessible and a new TODO work creation should start with its contents. 
- ...

## Depends On

- Building the templates

## Tasks

To be filled out after related tasks are created.

- [x] Created a Pull Request template
- [x] Created a Bug reporttemplate 
- [x] Created a Feature or User Story template
- [x] Created a Task template
- [x] Created a TODO template

## Details

- References to documentation on creating Pull Request template: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
- References to documentation on creating an issue template: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
- ...

**Comment by ayomustapha** [comment]
The PR, Bug, Task, Feature or User Story and TODO templates have been created. Theor PRs have been review and checked into the main branch. Each of the templates have been tested ok.
